name: Python AI Service CI/CD

on:
  push:
    branches: [ "main", "master" ]

concurrency:
  group: recommendationService-prod
  cancel-in-progress: true

jobs:
  build-and-run:
    runs-on: self-hosted
    # max-parallel: 1   # лише якщо буде декілька job-ів

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure Python 3.11 is available
        run: python3.11 --version

      - name: Set up swap (для low RAM)
        run: |
          sudo fallocate -l 2G /swapfile || sudo dd if=/dev/zero of=/swapfile bs=1M count=2048
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
        continue-on-error: true

      - name: Install system build dependencies (для scikit-surprise та pandas)
        run: |
          sudo yum groupinstall "Development Tools" -y
          sudo yum install -y gcc-c++ python3-devel

      - name: Set up venv and install dependencies
        run: |
          python3.11 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install --only-binary=:all: -r requirements.txt || pip install -r requirements.txt

      - name: Kill previous AI service
        run: |
          if lsof -i :8000; then
            sudo kill -9 $(sudo lsof -t -i:8000) || true
          fi

      - name: Run AI service
        run: |
          source venv/bin/activate
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
